import {defineField, defineType} from 'sanity'

export const experiencePageInternalNav = defineType({
  name: 'experiencePageInternalNav',
  title: 'Menú interno (sticky)',
  type: 'object',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'subtitle',
      title: 'Subtitle',
      type: 'text',
      rows: 2,
      validation: (Rule) => Rule.max(240),
    }),
    defineField({
      name: 'ctaSmartLink',
      title: 'Sticky bar CTA',
      type: 'smartLink',
      description: 'Primary control for the sticky internal menu book button.',
    }),
    defineField({
      name: 'ctaVisible',
      title: 'Show CTA on site',
      type: 'boolean',
      initialValue: true,
    }),
    defineField({
      name: 'items',
      title: 'Items',
      type: 'array',
      of: [{type: 'internalNavItem'}],
      validation: (Rule) => Rule.max(24),
    }),
    defineField({
      name: 'fromLabel',
      title: 'From label (read-only in Studio)',
      type: 'string',
      validation: (Rule) => Rule.max(40),
      readOnly: true,
      hidden: true,
      description: 'Derived on the site from the linked Experience. Preserved for older content.',
    }),
    defineField({
      name: 'priceText',
      title: 'Price text (read-only in Studio)',
      type: 'string',
      validation: (Rule) => Rule.max(40),
      readOnly: true,
      hidden: true,
      description: 'Derived on the site from the linked Experience. Preserved for older content.',
    }),
    defineField({
      name: 'priceSuffix',
      title: 'Price suffix (read-only in Studio)',
      type: 'string',
      validation: (Rule) => Rule.max(80),
      readOnly: true,
      hidden: true,
      description: 'Derived on the site from the linked Experience. Preserved for older content.',
    }),
    defineField({
      name: 'ctaLabel',
      title: 'CTA label (legacy)',
      type: 'string',
      validation: (Rule) => Rule.max(80),
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'ctaUrl',
      title: 'CTA URL (legacy)',
      type: 'url',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'bookCta',
      title: 'CTA (legacy linkWithLabel)',
      type: 'cta',
      hidden: true,
      description: 'Deprecated — use Sticky bar CTA above. Data preserved.',
    }),
    defineField({
      name: 'bookCtaSmartLink',
      title: 'CTA (legacy smart link)',
      type: 'smartLink',
      hidden: true,
      options: {relaxTargetValidation: true},
      description: 'Deprecated duplicate — use Sticky bar CTA (`ctaSmartLink`) only.',
    }),
  ],
})
