import {defineField, defineType} from 'sanity'

export const landingHero = defineType({
  name: 'landingHero',
  title: 'Hero (this page)',
  type: 'object',
  description:
    'Editorial overrides for this landing URL. Product facts (price, gallery photos, program type) come from the linked **Experience** in the library.',
  fields: [
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow (optional)',
      type: 'string',
      validation: (r) => r.max(80),
      hidden: true,
      description: 'Legacy — hidden. Empty = site default.',
    }),
    defineField({
      name: 'headline',
      title: 'Title (experience hero)',
      type: 'string',
      validation: (r) => r.max(120),
      description: 'Optional. Replaces the experience name in the hero for this URL only. Empty = experience name.',
    }),
    defineField({
      name: 'headlineSub',
      title: 'Short description',
      type: 'text',
      rows: 2,
      description: 'Optional. Shown under the title. Empty = experience tagline.',
    }),
    defineField({
      name: 'pills',
      title: 'Highlights (plain text, max 6)',
      type: 'array',
      of: [{type: 'string'}],
      validation: (r) => r.max(6),
      description: 'Optional lines under the title (glass pills). Empty = derived from the experience (program, route, duration).',
    }),
    defineField({
      name: 'manualRatingValue',
      title: 'Manual rating value',
      type: 'string',
      validation: (r) => r.max(12),
      description: 'Displayed next to the stars (e.g. 4.9). Optional — overrides the default until global reviews are wired.',
    }),
    defineField({
      name: 'manualReviewCount',
      title: 'Manual review count',
      type: 'number',
      validation: (r) => r.min(0).integer(),
      description: 'Number of reviews (e.g. 12). Shown as “· N reviews”. Optional.',
    }),
    defineField({
      name: 'manualReviewProviderLabel',
      title: 'Review provider label (optional)',
      type: 'string',
      validation: (r) => r.max(40),
      description: 'Short suffix after the review count when needed (e.g. Google).',
    }),
    defineField({
      name: 'heroPricePrefix',
      title: 'Price prefix',
      type: 'string',
      initialValue: 'from',
      validation: (r) => r.max(24),
      description: 'Light text before the amount (e.g. “from”). Empty = hide prefix. Default in Studio only — set on this Experience Page.',
    }),
    defineField({
      name: 'heroPriceSuffix',
      title: 'Price suffix',
      type: 'string',
      initialValue: 'per person',
      validation: (r) => r.max(40),
      description: 'Line under the amount (e.g. “per person”). Empty = hide suffix. Default in Studio only.',
    }),
    defineField({
      name: 'heroPriceFootnote',
      title: 'Price footnote',
      type: 'string',
      initialValue: 'all inclusive',
      validation: (r) => r.max(60),
      description:
        'Second line under the suffix. Empty or **Hide price footnote** = hidden on the main hero. Default in Studio only.',
    }),
    defineField({
      name: 'hideHeroPriceFootnote',
      title: 'Hide price footnote',
      type: 'boolean',
      initialValue: false,
      description:
        'When enabled, the footnote line is hidden on the main hero even if **Price footnote** has text. Use this to reliably remove “all inclusive” (clearing the text field alone may not persist as empty in Sanity).',
    }),
    defineField({
      name: 'priceLine',
      title: 'Price line (legacy override)',
      type: 'string',
      validation: (r) => r.max(40),
      hidden: true,
      description: 'Hidden — price comes from the linked Experience. Kept for older documents.',
    }),
    defineField({
      name: 'priceSub',
      title: 'Price detail / suffix (legacy)',
      type: 'string',
      validation: (r) => r.max(80),
      hidden: true,
      description: 'Hidden — use experience pricing. Kept for compatibility.',
    }),
    defineField({
      name: 'useProductPrice',
      title: 'Use linked experience price when override empty',
      type: 'boolean',
      initialValue: true,
      hidden: true,
      description: 'Hidden — resolver always prefers Experience. Legacy field.',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero image override (legacy)',
      type: 'imageWithAlt',
      hidden: true,
      description: 'Hidden — first photos come from the Experience gallery. Kept for old landings.',
    }),
    defineField({
      name: 'bookCta',
      title: 'CTA principal (reserva) — legacy',
      type: 'cta',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'bookCtaSmartLink',
      title: 'CTA principal (reserva)',
      type: 'smartLink',
      description: 'Primary editor control for the hero booking button.',
    }),
  ],
})
