import {defineArrayMember, defineField, defineType} from 'sanity'
import {PageSectionVisibleField} from '../components/pageSection/PageSectionVisibleField'
import {validateImageRole} from '../lib/ecotoneImageRoleValidation'

const pageSectionVisibleUi = (sectionKey, group) =>
  defineField({
    name: `${sectionKey}SectionVisibilityUi`,
    title: 'Section visibility',
    type: 'string',
    group,
    components: {input: PageSectionVisibleField},
    options: {sectionKey},
  })

/**
 * Singleton `/about` — all on-page copy & media (no separate knowledge base).
 * `_id` must be `aboutPage` (see `CMS_IDS.aboutPage`).
 */
export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'About page',
  type: 'document',
  groups: [
    {name: 'general', title: 'General & SEO', default: true},
    {name: 'hero', title: 'Hero'},
    {name: 'who', title: 'Who we are'},
    {name: 'why', title: 'Why we exist'},
    {name: 'crees', title: 'Ecotone + CREES'},
    {name: 'different', title: 'What makes us different'},
    {name: 'way', title: 'Our way'},
    {name: 'people', title: 'People'},
    {name: 'bcorp', title: 'B Corp'},
    {name: 'proof', title: 'Proof / Growing platform'},
    {name: 'partners', title: 'Partners'},
    {name: 'finalCta', title: 'Final CTA'},
  ],
  fields: [
    defineField({
      name: 'internalTitle',
      title: 'Internal title (Studio only)',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug / URL',
      type: 'slug',
      group: 'general',
      options: {source: 'internalTitle', maxLength: 96},
      initialValue: {_type: 'slug', current: 'about'},
      description: 'Must stay `about` for the /about route.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'general',
    }),
    defineField({
      name: 'sectionModules',
      title: 'sectionModules (internal)',
      type: 'array',
      of: [{type: 'pageModule'}],
      hidden: true,
      group: 'general',
    }),

    // --- Hero ---
    pageSectionVisibleUi('hero', 'hero'),
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
      validation: validateImageRole('hero'),
    }),
    defineField({name: 'heroImageAlt', title: 'Hero image alt', type: 'string', group: 'hero'}),
    defineField({name: 'heroEyebrow', title: 'Eyebrow', type: 'string', group: 'hero'}),
    defineField({
      name: 'heroTitle',
      title: 'Title',
      type: 'text',
      rows: 3,
      description: 'One or two lines. Use a line break between lines.',
      group: 'hero',
    }),
    defineField({name: 'heroTagline', title: 'Tagline', type: 'text', rows: 3, group: 'hero'}),
    defineField({
      name: 'heroPrimaryCta',
      title: 'Primary CTA (legacy)',
      type: 'linkWithLabel',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroSecondaryCta',
      title: 'Secondary CTA (legacy)',
      type: 'linkWithLabel',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroPrimarySmartLink',
      title: 'Primary CTA',
      type: 'smartLink',
      group: 'hero',
      description: 'Primary editor control for the hero button.',
    }),
    defineField({
      name: 'heroSecondarySmartLink',
      title: 'Secondary CTA',
      type: 'smartLink',
      group: 'hero',
      description: 'Primary editor control for the secondary hero button.',
    }),

    // --- Who we are ---
    pageSectionVisibleUi('who', 'who'),
    defineField({
      name: 'whoSectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'who',
      initialValue: 'who',
    }),
    defineField({
      name: 'whoImage',
      title: 'Image',
      type: 'image',
      group: 'who',
      options: {hotspot: true},
      validation: validateImageRole('editorial'),
    }),
    defineField({name: 'whoImageAlt', title: 'Image alt', type: 'string', group: 'who'}),
    defineField({name: 'whoEyebrow', title: 'Eyebrow', type: 'string', group: 'who'}),
    defineField({name: 'whoTitle', title: 'Title', type: 'string', group: 'who'}),
    defineField({
      name: 'whoBodyParagraphs',
      title: 'Body paragraphs',
      type: 'array',
      group: 'who',
      of: [{type: 'aboutPageParagraph'}],
    }),
    defineField({
      name: 'whoPills',
      title: 'Pills',
      type: 'array',
      group: 'who',
      of: [{type: 'aboutPagePill'}],
      validation: (Rule) => Rule.max(12),
    }),

    // --- Why we exist ---
    pageSectionVisibleUi('why', 'why'),
    defineField({
      name: 'whySectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'why',
      initialValue: 'why',
    }),
    defineField({name: 'whyEyebrow', title: 'Eyebrow', type: 'string', group: 'why'}),
    defineField({
      name: 'whyTitle',
      title: 'Title',
      type: 'text',
      rows: 3,
      description: 'One or two lines; use a line break between lines.',
      group: 'why',
    }),
    defineField({name: 'whyBody', title: 'Body', type: 'text', rows: 5, group: 'why'}),

    // --- Ecotone + CREES ---
    pageSectionVisibleUi('creesIntegration', 'crees'),
    defineField({
      name: 'creesSectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'crees',
      initialValue: 'ecotone-crees',
    }),
    defineField({name: 'creesEyebrow', title: 'Eyebrow', type: 'string', group: 'crees'}),
    defineField({name: 'creesTitle', title: 'Title', type: 'string', group: 'crees'}),
    defineField({name: 'creesSubtitle', title: 'Subtitle', type: 'string', group: 'crees'}),
    defineField({
      name: 'creesBodyParagraphs',
      title: 'Body paragraphs',
      type: 'array',
      group: 'crees',
      of: [{type: 'aboutPageParagraph'}],
      description: 'First paragraph appears above the combined logo; remaining paragraphs below.',
    }),
    defineField({
      name: 'creesImage',
      title: 'Image',
      type: 'image',
      group: 'crees',
      options: {hotspot: true},
      validation: validateImageRole('editorial'),
    }),
    defineField({name: 'creesImageAlt', title: 'Image alt', type: 'string', group: 'crees'}),
    defineField({
      name: 'creesLockup',
      title: 'Combined Ecotone + CREES logo',
      type: 'image',
      group: 'crees',
      description: 'Single combined SVG/PNG lockup (not separate logos).',
      options: {accept: 'image/svg+xml,image/png'},
    }),
    defineField({name: 'creesLockupAlt', title: 'Lockup alt', type: 'string', group: 'crees'}),
    defineField({
      name: 'creesCtaSmartLink',
      title: 'CTA',
      type: 'smartLink',
      group: 'crees',
      description: 'Uses the shared Link selector (same as Hero and other CTAs).',
    }),
    defineField({
      name: 'creesCtaLabel',
      title: 'CTA label (legacy)',
      type: 'string',
      group: 'crees',
      hidden: true,
      description: 'Legacy — use CTA smart link above.',
    }),
    defineField({
      name: 'creesCtaHref',
      title: 'CTA URL (legacy)',
      type: 'string',
      group: 'crees',
      hidden: true,
      description: 'Legacy — use CTA smart link above.',
    }),

    // --- What makes us different ---
    pageSectionVisibleUi('different', 'different'),
    defineField({
      name: 'diffSectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'different',
      initialValue: 'different',
    }),
    defineField({name: 'diffEyebrow', title: 'Eyebrow', type: 'string', group: 'different'}),
    defineField({name: 'diffTitle', title: 'Title', type: 'string', group: 'different'}),
    defineField({
      name: 'diffIntro',
      title: 'Intro (left column)',
      type: 'text',
      rows: 3,
      group: 'different',
    }),
    defineField({
      name: 'diffImage',
      title: 'Editorial image (left column)',
      type: 'image',
      group: 'different',
      options: {hotspot: true},
      validation: validateImageRole('editorial'),
    }),
    defineField({name: 'diffImageAlt', title: 'Editorial image alt', type: 'string', group: 'different'}),
    defineField({
      name: 'diffCards',
      title: 'Principles',
      type: 'array',
      group: 'different',
      of: [{type: 'aboutPageDiffCard'}],
      validation: (Rule) => Rule.max(8),
      description: 'Order in this list becomes 01, 02, 03… on the page. Icons are not shown.',
    }),

    // --- Our way ---
    pageSectionVisibleUi('way', 'way'),
    defineField({
      name: 'waySectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'way',
      initialValue: 'way',
    }),
    defineField({
      name: 'wayImage',
      title: 'Image',
      type: 'image',
      group: 'way',
      options: {hotspot: true},
    }),
    defineField({name: 'wayImageAlt', title: 'Image alt', type: 'string', group: 'way'}),
    defineField({name: 'wayEyebrow', title: 'Eyebrow', type: 'string', group: 'way'}),
    defineField({name: 'wayTitle', title: 'Title', type: 'string', group: 'way'}),
    defineField({
      name: 'wayBodyParagraphs',
      title: 'Body paragraphs',
      type: 'array',
      group: 'way',
      of: [{type: 'aboutPageParagraph'}],
    }),
    defineField({name: 'wayPullquote', title: 'Pull quote', type: 'text', rows: 2, group: 'way'}),

    // --- People ---
    pageSectionVisibleUi('people', 'people'),
    defineField({
      name: 'peopleSectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'people',
      initialValue: 'people',
    }),
    defineField({name: 'peopleEyebrow', title: 'Eyebrow', type: 'string', group: 'people'}),
    defineField({name: 'peopleTitle', title: 'Title', type: 'string', group: 'people'}),
    defineField({name: 'peopleBody', title: 'Intro body', type: 'text', rows: 4, group: 'people'}),
    defineField({
      name: 'peopleInitialVisibleCount',
      title: 'Initially visible people',
      type: 'number',
      group: 'people',
      initialValue: 4,
      description: 'Show this many people before “View more people”. Default 4.',
      validation: (Rule) => Rule.min(1).max(24).integer(),
    }),
    defineField({
      name: 'peopleCards',
      title: 'People',
      type: 'array',
      group: 'people',
      of: [{type: 'aboutPagePerson'}],
      description: 'Unlimited list; drag to reorder. LinkedIn is optional per person.',
    }),

    // --- B Corp ---
    pageSectionVisibleUi('bcorp', 'bcorp'),
    defineField({
      name: 'bcorpSectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'bcorp',
      initialValue: 'bcorp',
    }),
    defineField({name: 'bcorpEyebrow', title: 'Eyebrow', type: 'string', group: 'bcorp'}),
    defineField({name: 'bcorpTitle', title: 'Title', type: 'string', group: 'bcorp'}),
    defineField({
      name: 'bcorpBodyParagraphs',
      title: 'Body paragraphs',
      type: 'array',
      group: 'bcorp',
      of: [{type: 'aboutPageParagraph'}],
    }),
    defineField({
      name: 'bcorpLogo',
      title: 'B Corp logo (black SVG preferred)',
      type: 'image',
      group: 'bcorp',
      description:
        'Official black B Corp mark. Rendered white on the dark section via CSS mask. Prefer SVG.',
      options: {accept: 'image/svg+xml,image/png'},
    }),
    defineField({name: 'bcorpLogoAlt', title: 'Logo alt', type: 'string', group: 'bcorp'}),
    defineField({
      name: 'bcorpPrimarySmartLink',
      title: 'Primary CTA',
      type: 'smartLink',
      group: 'bcorp',
      description: 'Shared Link selector — Ecotone listing on B Corp (or placeholder until set).',
    }),
    defineField({
      name: 'bcorpSecondarySmartLink',
      title: 'Secondary CTA',
      type: 'smartLink',
      group: 'bcorp',
      description: 'Shared Link selector — general B Corp information.',
    }),
    defineField({
      name: 'bcorpPrimaryCtaLabel',
      title: 'Primary CTA label (legacy)',
      type: 'string',
      group: 'bcorp',
      hidden: true,
      description: 'Legacy — use Primary CTA smart link above.',
    }),
    defineField({
      name: 'bcorpPrimaryCtaHref',
      title: 'Primary CTA URL (legacy)',
      type: 'string',
      group: 'bcorp',
      hidden: true,
      description: 'Legacy — use Primary CTA smart link above.',
    }),
    defineField({
      name: 'bcorpSecondaryCtaLabel',
      title: 'Secondary CTA label (legacy)',
      type: 'string',
      group: 'bcorp',
      hidden: true,
      description: 'Legacy — use Secondary CTA smart link above.',
    }),
    defineField({
      name: 'bcorpSecondaryCtaHref',
      title: 'Secondary CTA URL (legacy)',
      type: 'string',
      group: 'bcorp',
      hidden: true,
      description: 'Legacy — use Secondary CTA smart link above.',
    }),

    // --- Proof ---
    pageSectionVisibleUi('proof', 'proof'),
    defineField({
      name: 'proofSectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'proof',
      initialValue: 'proof',
    }),
    defineField({name: 'proofEyebrow', title: 'Eyebrow', type: 'string', group: 'proof'}),
    defineField({name: 'proofTitle', title: 'Title', type: 'string', group: 'proof'}),
    defineField({name: 'proofBody', title: 'Body', type: 'text', rows: 4, group: 'proof'}),
    defineField({
      name: 'proofStats',
      title: 'Stats',
      type: 'array',
      group: 'proof',
      of: [{type: 'aboutPageStat'}],
      validation: (Rule) => Rule.max(8),
    }),
    defineField({
      name: 'proofCertLabel',
      title: 'Cert row label (e.g. “Recognised by”)',
      type: 'string',
      group: 'proof',
    }),
    defineField({
      name: 'proofCerts',
      title: 'Certification labels',
      type: 'array',
      group: 'proof',
      of: [{type: 'string'}],
      validation: (Rule) => Rule.max(20),
    }),

    // --- Partners ---
    pageSectionVisibleUi('partners', 'partners'),
    defineField({
      name: 'partnersEyebrow',
      title: 'Eyebrow (optional)',
      type: 'string',
      group: 'partners',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'partnersTitle',
      title: 'Section title',
      type: 'string',
      group: 'partners',
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: 'partnersBody',
      title: 'Body',
      type: 'text',
      rows: 3,
      group: 'partners',
      description: 'Optional text under the title.',
    }),
    defineField({
      name: 'partnersEmptyMessage',
      title: 'When no partners selected — message (optional)',
      type: 'text',
      rows: 3,
      group: 'partners',
      description: 'Shown when the reference list is empty. Leave empty to hide the band.',
    }),
    defineField({
      name: 'partnerRefs',
      title: 'Partners on About (order)',
      type: 'array',
      group: 'partners',
      of: [
        defineArrayMember({
          type: 'reference',
          to: [{type: 'partner'}],
          options: {disableNew: true},
        }),
      ],
      description:
        'Select which partners appear in this band and drag to reorder. Content lives on each Partner document only.',
      validation: (Rule) =>
        Rule.custom((refs) => {
          if (!Array.isArray(refs)) return true
          const ids = refs.map((r) => r?._ref).filter(Boolean)
          return new Set(ids).size === ids.length ? true : 'Each partner can only appear once'
        }),
    }),

    // --- Final CTA ---
    pageSectionVisibleUi('finalCta', 'finalCta'),
    defineField({
      name: 'finalSectionId',
      title: 'Section HTML id',
      type: 'string',
      group: 'finalCta',
      initialValue: 'contact',
    }),
    defineField({
      name: 'reserveCtaSettings',
      title: 'Reserve CTA (final block)',
      type: 'reserveCtaSettings',
      group: 'finalCta',
      description:
        'Editorial + booking card. Price defaults to lowest **active** experience unless overridden.',
    }),
    defineField({
      name: 'finalEyebrow',
      title: 'Eyebrow (legacy)',
      type: 'string',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'finalTitle',
      title: 'Title (legacy)',
      type: 'string',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'finalBody',
      title: 'Body (legacy)',
      type: 'text',
      rows: 4,
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'finalButtons',
      title: 'Buttons (legacy)',
      type: 'array',
      group: 'finalCta',
      of: [{type: 'aboutPageCtaButton'}],
      validation: (Rule) => Rule.max(6),
      hidden: true,
      description: 'Legacy — use Reserve CTA smart links.',
    }),
    defineField({
      name: 'finalTrustItems',
      title: 'Trust strip items (legacy)',
      type: 'array',
      group: 'finalCta',
      of: [{type: 'aboutPageTrustItem'}],
      validation: (Rule) => Rule.max(8),
      hidden: true,
      description: 'Legacy — trust strip is fixed on the site.',
    }),
  ],
  preview: {
    prepare() {
      return {title: 'About page', subtitle: '/about'}
    },
  },
})
