import {defineField, defineType} from 'sanity'
import {StudioSectionTabField} from '../components/experiencePageStudio/StudioSectionTabField'
import {ExperienceKcOrderInput} from '../components/experiencePage/ExperienceKcOrderInput'

const previewField = (name, title, group, section, extraOptions = {}) =>
  defineField({
    name,
    title,
    type: 'string',
    readOnly: true,
    group,
    description:
      'Toggle visibility and optional eyebrow, title, and intro for this section on **this URL** (stored in sectionModules).',
    components: {input: StudioSectionTabField},
    options: {section, hidePreview: true, ...extraOptions},
  })

/**
 * Landing de experiencia: presentación (URL, hero, SEO, curación).
 * Overrides por bloque se persisten en `sectionModules` (campo oculto), editados desde cada pestaña.
 */
export const experiencePage = defineType({
  name: 'experiencePage',
  title: 'Experience page (landing)',
  type: 'document',
  description:
    'Presentation for a single public experience URL. Linked **Experience** (library) is the product source of truth; this document controls layout, section copy, selection, and overrides.',
  groups: [
    {name: 'general', title: 'General', default: true},
    {name: 'internalNav', title: 'Internal menu'},
    {name: 'hero', title: 'Hero'},
    {name: 'highlights', title: 'Highlights'},
    {name: 'overview', title: 'Overview'},
    {name: 'itinerary', title: 'Itinerary'},
    {name: 'lodge', title: 'Lodge'},
    {name: 'wildlife', title: 'Wildlife'},
    {name: 'included', title: 'Includes'},
    {name: 'tech', title: 'Technology'},
    {name: 'gallery', title: 'Gallery'},
    {name: 'when', title: 'When to visit'},
    {name: 'beforeYou', title: 'Guía'},
    {name: 'reviews', title: 'Reviews'},
    {name: 'terms', title: 'Terms'},
    {name: 'resources', title: 'Resources'},
    {name: 'faq', title: 'FAQs'},
    {name: 'related', title: 'Also like'},
    {name: 'reserve', title: 'Reserve'},
    {name: 'legacy', title: 'Legacy'},
  ],
  fields: [
    // --- General ---
    defineField({
      name: 'internalTitle',
      title: 'Nombre interno (solo Studio)',
      type: 'string',
      group: 'general',
      description: 'Para la lista y el equipo. No es el H1 del sitio.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug / URL',
      type: 'slug',
      group: 'general',
      options: {source: 'internalTitle', maxLength: 96},
      validation: (Rule) => Rule.required(),
      description: 'Segmento de ruta (p. ej. `soqtapata-pristine-immersion`).',
    }),
    defineField({
      name: 'headerNavOrder',
      title: 'Header mega menu order',
      type: 'number',
      group: 'general',
      description:
        'Lower numbers appear first within each program group (Classic / Signature / Learning). Leave empty for alphabetical by experience name.',
      validation: (Rule) =>
        Rule.custom((value) => {
          if (value === undefined || value === null) return true
          if (!Number.isInteger(value)) return 'Use a whole number'
          if (value < 0 || value > 999) return 'Between 0 and 999'
          return true
        }),
    }),
    defineField({
      name: 'experience',
      title: 'Experiencia vinculada (fuente principal)',
      type: 'reference',
      to: [{type: 'experience'}],
      group: 'general',
      validation: (Rule) => Rule.required(),
      options: {disableNew: false},
      description:
        'Canonical program data (itinerary, price, gallery, etc.) is edited in **Content library → Experiences**. This document controls this URL’s presentation and overrides only.',
    }),
    defineField({
      name: 'seo',
      title: 'SEO básico (esta URL)',
      type: 'seo',
      group: 'general',
      description: 'Título y descripción meta de **esta** landing. Pueden diferir del SEO del documento Experiencia.',
    }),

    // --- Internal menu ---
    previewField(
      'stPrevInternalNav',
      'Section presentation',
      'internalNav',
      'internalNav',
      {hidePreview: true},
    ),
    defineField({
      name: 'internalNav',
      title: 'Internal navigation (sticky)',
      type: 'experiencePageInternalNav',
      group: 'internalNav',
      description: 'Title, subtitle, anchor items, and sticky CTA. Price line on the site is derived from the linked Experience.',
    }),

    // --- Hero ---
    previewField('stPrevHero', 'Section presentation', 'hero', 'hero', {hidePreview: true}),
    defineField({
      name: 'pageHero',
      title: 'Hero — copy & CTAs (this page)',
      type: 'landingHero',
      group: 'hero',
      description:
        'Title, short description, highlight lines, rating display, and booking CTA. Price and gallery photos come from the linked Experience.',
    }),

    // --- Highlights (= barra de stats bajo el hero) ---
    previewField(
      'stPrevHighlights',
      'Section presentation',
      'highlights',
      'highlights',
    ),
    defineField({
      name: 'snapshotHighlightOrderKeys',
      title: 'Snapshot highlights — select & order',
      type: 'array',
      of: [{type: 'string'}],
      group: 'highlights',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'snapshotHighlights'},
      validation: (Rule) => Rule.max(6),
      description:
        'From the linked Experience → tab **Highlights** → **Snapshot highlights**. Order = display order; items not listed are hidden. Empty = first 6 in KC order.',
    }),
    defineField({
      name: 'snapshotStatSelections',
      title: 'Stats bar — legacy slot picks (hidden)',
      type: 'array',
      of: [{type: 'experiencePageSnapshotStatPick'}],
      group: 'highlights',
      hidden: true,
      description: 'Deprecated — use **Snapshot highlights — select & order** above.',
    }),

    // --- Overview … FAQs: preview + overrides vía StudioSectionTabField ---
    previewField(
      'stPrevOverview',
      'Section presentation',
      'overview',
      'overview',
    ),
    defineField({
      name: 'overviewHighlightKeys',
      title: 'Overview highlight lines — select & order',
      type: 'array',
      of: [{type: 'string'}],
      group: 'overview',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'overviewHighlights'},
      validation: (Rule) => Rule.max(12),
      description:
        'Lines come from the linked Experience → tab **③ Overview · datos** → **Overview highlight lines**. Order = display order; items not listed are hidden. Empty = show all in KC order.',
    }),
    defineField({
      name: 'overviewHighlightOrder',
      title: 'Legacy: overview highlights — indices (hidden)',
      type: 'array',
      of: [{type: 'number'}],
      group: 'overview',
      hidden: true,
      validation: (Rule) => Rule.max(12),
      description: 'Deprecated 0-based indices. Preserved for old documents; not shown in the editor.',
    }),
    previewField(
      'stPrevItinerary',
      'Section presentation',
      'itinerary',
      'itinerary',
    ),
    previewField(
      'stPrevLodge',
      'Section presentation',
      'lodge',
      'lodge',
    ),
    defineField({
      name: 'lodgesOrderKeys',
      title: 'Lodges on this programme — select & order',
      type: 'array',
      of: [{type: 'string'}],
      group: 'lodge',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'lodges'},
      validation: (Rule) => Rule.max(12),
      description:
        'Lodges are defined on the linked Experience → tab **⑤ Lodges** → **Lodges on this programme**. Pick which appear here and in what order. Names and descriptions always come from Lodge KC. Empty = show all KC lodges in programme order.',
    }),
    defineField({
      name: 'lodgePageLink',
      title: 'Lodge page (legacy — single lodge)',
      type: 'reference',
      to: [{type: 'lodgePage'}],
      group: 'lodge',
      options: {disableNew: false},
      hidden: true,
      description: 'Deprecated — each lodge card uses its Lodge Page slug from Lodge KC.',
    }),
    defineField({
      name: 'lodgeCtaVisible',
      title: 'Show lodge card CTAs',
      type: 'boolean',
      initialValue: true,
      group: 'lodge',
      description: 'When off, hides “View lodge page” buttons on all lodge cards on this landing.',
    }),
    defineField({
      name: 'lodgeCtaLabel',
      title: 'Default lodge CTA label',
      type: 'string',
      group: 'lodge',
      initialValue: 'View full lodge page',
      validation: (Rule) => Rule.max(80),
      hidden: ({parent}) => parent?.lodgeCtaVisible === false,
      description:
        'Fallback button label when a lodge row has no CTA label in Experience KC. Link is always `/lodges/{slug}` from each lodge’s published Lodge Page.',
    }),
    defineField({
      name: 'lodgeCtaSmartLink',
      title: 'Lodge CTA (legacy smart link)',
      type: 'smartLink',
      group: 'lodge',
      hidden: true,
      description: 'Deprecated — link is always `/lodges/{slug}` from **Lodge page** selection.',
    }),
    previewField(
      'stPrevWildlife',
      'Section presentation',
      'wildlife',
      'wildlife',
    ),
    defineField({
      name: 'wildlifeOrderKeys',
      title: 'Wildlife species — select & order',
      type: 'array',
      of: [{type: 'string'}],
      group: 'wildlife',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'wildlife'},
      validation: (Rule) => Rule.max(12),
      description:
        'Pick species from the linked Experience. Order = display order; not listed = hidden. Empty = show all in Knowledge Center order.',
    }),
    defineField({
      name: 'wildlifeDisplayOrder',
      title: 'Legacy: wildlife — indices (hidden)',
      type: 'array',
      of: [{type: 'number'}],
      group: 'wildlife',
      hidden: true,
      validation: (Rule) => Rule.max(10),
      description: 'Deprecated 0-based indices. Preserved for old documents.',
    }),
    previewField(
      'stPrevIncludes',
      'Section presentation',
      'included',
      'includes',
    ),
    defineField({
      name: 'includesOrderKeys',
      title: 'Included items — select & order',
      type: 'array',
      of: [{type: 'string'}],
      group: 'included',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'includes'},
      validation: (Rule) => Rule.max(20),
      description: 'From the linked Experience “Incluye” list. Empty = show all in default order.',
    }),
    defineField({
      name: 'notIncludesOrderKeys',
      title: 'Not included — select & order',
      type: 'array',
      of: [{type: 'string'}],
      group: 'included',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'notIncludes'},
      validation: (Rule) => Rule.max(20),
      description: 'From the linked Experience “No incluye” list. Empty = show all in default order.',
    }),
    defineField({
      name: 'includesDisplayOrder',
      title: 'Legacy: included — indices (hidden)',
      type: 'array',
      of: [{type: 'number'}],
      group: 'included',
      hidden: true,
      validation: (Rule) => Rule.max(20),
      description: 'Deprecated.',
    }),
    defineField({
      name: 'notIncludesDisplayOrder',
      title: 'Legacy: not included — indices (hidden)',
      type: 'array',
      of: [{type: 'number'}],
      group: 'included',
      hidden: true,
      validation: (Rule) => Rule.max(20),
      description: 'Deprecated.',
    }),
    previewField(
      'stPrevTech',
      'Section presentation',
      'tech',
      'tech',
    ),
    defineField({
      name: 'techProductRefs',
      title: '4. Selección y orden',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'technologyProduct'}]}],
      group: 'tech',
      validation: (Rule) => Rule.max(12),
      description:
        'Selecciona y ordena los productos que se mostrarán en esta landing.',
    }),
    defineField({
      name: 'includedTechProductIds',
      title: 'IDs estables de productos «incluidos en el pack» (opcional)',
      type: 'array',
      of: [{type: 'string'}],
      group: 'tech',
      description: 'Alinea con `stableId` de cada producto (badges, etc.).',
    }),
    previewField(
      'stPrevGallery',
      'Section presentation',
      'gallery',
      'gallery',
    ),
    defineField({
      name: 'galleryOrderKeys',
      title: 'Gallery — select & order (from Experience)',
      type: 'array',
      of: [{type: 'string'}],
      group: 'gallery',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'gallery'},
      validation: (Rule) => Rule.max(20),
      description:
        'Pick and order photos from the linked Experience Knowledge Center gallery. Only selected images appear on this URL. Empty = show all KC gallery images in KC order.',
    }),
    previewField(
      'stPrevWhen',
      'Section presentation',
      'when',
      'when',
    ),
    previewField(
      'stPrevBefore',
      'Section presentation',
      'beforeYou',
      'beforeYou',
    ),
    previewField(
      'stPrevReviews',
      'Section presentation',
      'reviews',
      'reviews',
    ),
    defineField({
      name: 'reviewsSection',
      title: 'Reviews — quotes & cards',
      type: 'experiencePageReviewsSection',
      group: 'reviews',
      description:
        'Rotating quotes (max 3) and review cards (max 4). Section eyebrow / title / intro: **Section presentation** above. Global rating: Settings → Reviews.',
    }),
    defineField({
      name: 'reviewRefs',
      title: 'Legacy — review refs',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'review'}]}],
      group: 'reviews',
      hidden: true,
      validation: (Rule) => Rule.max(24),
    }),
    defineField({
      name: 'reviewsLayout',
      title: 'Legacy — layout / rating copy',
      type: 'reviewsLayoutBlock',
      group: 'reviews',
      hidden: true,
    }),
    previewField(
      'stPrevTerms',
      'Section presentation',
      'terms',
      'terms',
    ),
    defineField({
      name: 'termsOrderKeys',
      title: 'Terms sections — select & order',
      type: 'array',
      of: [{type: 'string'}],
      group: 'terms',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'termsPanels'},
      validation: (Rule) => Rule.max(24),
      description:
        'Pick accordion sections from the central **Terms & Conditions** Knowledge Center (global + sections assigned to this Experience). Empty = show all applicable sections in CK order.',
    }),
    defineField({
      name: 'termsImportantNotesKeys',
      title: 'Legacy: important notes — select & order (hidden)',
      type: 'array',
      of: [{type: 'string'}],
      group: 'terms',
      hidden: true,
      validation: (Rule) => Rule.max(12),
      description: 'Deprecated — use **Terms sections** picker above.',
    }),
    defineField({
      name: 'termsImportantNotesOrder',
      title: 'Legacy: important notes — indices (hidden)',
      type: 'array',
      of: [{type: 'number'}],
      group: 'terms',
      hidden: true,
      validation: (Rule) => Rule.max(8),
      description: 'Deprecated.',
    }),
    defineField({
      name: 'termsDownloadEnabled',
      title: 'Show full terms PDF download button',
      type: 'boolean',
      initialValue: true,
      group: 'terms',
      description: 'When off, hides the download button in the Terms section (uses resolver defaults when unset).',
    }),
    defineField({
      name: 'termsDownloadLabel',
      title: 'Download button label',
      type: 'string',
      group: 'terms',
      validation: (Rule) => Rule.max(80),
      description: 'Overrides the default download label when set.',
    }),
    previewField(
      'stPrevResources',
      'Section presentation',
      'resources',
      'resources',
    ),
    defineField({
      name: 'resources',
      title: 'Legacy: Resources overrides (hidden)',
      type: 'experiencePageResources',
      group: 'resources',
      hidden: true,
      description: 'Deprecated. Resource cards are edited in the Experience library; this URL only picks order below.',
    }),
    defineField({
      name: 'resourcesFromExperienceKeys',
      title: 'Resources — select & order (from Experience)',
      type: 'array',
      of: [{type: 'string'}],
      group: 'resources',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'resources'},
      validation: (Rule) => Rule.max(15),
      description:
        'Pick and order download cards from the linked Experience. Section eyebrow / title / body: use **Section presentation** above. Empty = default order, all visible cards.',
    }),
    defineField({
      name: 'resourcesFromExperienceOrder',
      title: 'Legacy: resources — indices (hidden)',
      type: 'array',
      of: [{type: 'number'}],
      group: 'resources',
      hidden: true,
      validation: (Rule) => Rule.max(15),
      description: 'Deprecated 0-based indices.',
    }),
    previewField(
      'stPrevFaq',
      'Section presentation',
      'faq',
      'faq',
    ),
    defineField({
      name: 'faqOrderKeys',
      title: 'FAQs — select & order',
      type: 'array',
      of: [{type: 'string'}],
      group: 'faq',
      components: {input: ExperienceKcOrderInput},
      options: {kcSource: 'faq'},
      validation: (Rule) => Rule.max(15),
      description:
        'From Content Library → FAQs (global + FAQs assigned to the linked Experience KC). Empty = show all applicable FAQs in CK order. Legacy Experience KC FAQs used only when central FAQs CK has no matches.',
    }),
    defineField({
      name: 'faqDisplayOrder',
      title: 'Legacy: FAQs — indices (hidden)',
      type: 'array',
      of: [{type: 'number'}],
      group: 'faq',
      hidden: true,
      validation: (Rule) => Rule.max(15),
      description: 'Deprecated.',
    }),
    previewField(
      'stPrevRelated',
      'Section presentation',
      'related',
      'related',
    ),
    defineField({
      name: 'relatedExperienceRefs',
      title: 'Related experience pages (max 3)',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'experiencePage'}]}],
      group: 'related',
      validation: (Rule) => Rule.max(3),
      options: {
        filter: 'defined(slug.current) && defined(experience)',
      },
      description:
        'Pick up to 3 published experience **pages** to show in “Also like”. Only selected pages appear — no automatic suggestions.',
    }),
    defineField({
      name: 'showTailorMade',
      title: 'Show Tailor Made band',
      type: 'boolean',
      initialValue: false,
      group: 'related',
      description: 'When off, the Tailor Made band is hidden below the related experience cards.',
    }),
    defineField({
      name: 'tailorMadeEyebrow',
      title: 'Tailor Made — eyebrow',
      type: 'string',
      group: 'related',
      validation: (Rule) => Rule.max(80),
      hidden: ({parent}) => parent?.showTailorMade !== true,
    }),
    defineField({
      name: 'tailorMadeTitle',
      title: 'Tailor Made — title',
      type: 'string',
      group: 'related',
      validation: (Rule) => Rule.max(120),
      hidden: ({parent}) => parent?.showTailorMade !== true,
    }),
    defineField({
      name: 'tailorMadeBody',
      title: 'Tailor Made — subtitle',
      type: 'text',
      rows: 3,
      group: 'related',
      validation: (Rule) => Rule.max(400),
      hidden: ({parent}) => parent?.showTailorMade !== true,
    }),
    defineField({
      name: 'tailorMadeImage',
      title: 'Tailor Made — image (legacy)',
      type: 'image',
      group: 'related',
      options: {hotspot: true},
      hidden: true,
    }),
    defineField({
      name: 'tailorMadeAlt',
      title: 'Tailor Made — image alt (legacy)',
      type: 'string',
      group: 'related',
      validation: (Rule) => Rule.max(160),
      hidden: true,
    }),
    defineField({
      name: 'tailorMadeCtaLabel',
      title: 'Tailor Made — price line (legacy)',
      type: 'string',
      group: 'related',
      validation: (Rule) => Rule.max(80),
      hidden: true,
    }),
    defineField({
      name: 'tailorMadeCtaSmartLink',
      title: 'Tailor Made — CTA (smart link)',
      type: 'smartLink',
      group: 'related',
      description: 'Button label comes from the smart link. Hidden or off = no button.',
      hidden: ({parent}) => parent?.showTailorMade !== true,
    }),
    defineField({
      name: 'relatedSectionEyebrow',
      title: 'Legacy: Related section eyebrow (hidden)',
      type: 'string',
      group: 'related',
      hidden: true,
      validation: (Rule) => Rule.max(100),
      description: 'Deprecated — use **Section presentation** for copy. Kept for older documents.',
    }),
    defineField({
      name: 'relatedSectionTitle',
      title: 'Legacy: Related section title (hidden)',
      type: 'string',
      group: 'related',
      hidden: true,
      validation: (Rule) => Rule.max(120),
      description: 'Deprecated — use **Section presentation**.',
    }),

    defineField({
      name: 'stPrevReserve',
      title: 'Section presentation (legacy)',
      type: 'string',
      readOnly: true,
      group: 'reserve',
      hidden: true,
      description:
        'Deprecated — Reserve copy is edited in **Reserve CTA (#book)** below. Legacy sectionModules data preserved.',
    }),
    defineField({
      name: 'reserveCtaSettings',
      title: 'Reserve CTA (#book) — preferido',
      type: 'reserveCtaSettings',
      group: 'reserve',
      description:
        'Editorial, precio derivado de la experiencia, filas y CTAs. Tiene prioridad sobre el bloque legacy de abajo cuando hay valores.',
    }),
    defineField({
      name: 'reserveBlock',
      title: 'Override: bloque reserva (legacy)',
      type: 'landingReserveBlock',
      group: 'reserve',
      hidden: true,
      description:
        'Oculto: el sitio usa **Reserve CTA** y la experiencia vinculada. Se conserva en documentos antiguos como respaldo del resolver; no editar salvo migración.',
    }),
    defineField({
      name: 'sectionModules',
      title: 'sectionModules (persistencia interna)',
      type: 'array',
      of: [{type: 'pageModule'}],
      hidden: true,
      description:
        'Fuente única guardada para visible / eyebrow / título / intro por bloque. Se edita desde cada pestaña Overview→Reserve mediante el panel de overrides.',
    }),

    defineField({
      name: 'payloadV1',
      title: 'DEPRECATED: legacy JSON v1',
      type: 'text',
      rows: 4,
      group: 'legacy',
      readOnly: true,
      hidden: true,
      description: 'Migración antigua. El front no lo usa como fuente principal.',
    }),
  ],
  preview: {
    select: {t: 'internalTitle', slug: 'slug.current', exp: 'experience.name'},
    prepare: ({t, slug, exp}) => ({
      title: t || 'Experience page',
      subtitle: [slug && `/${slug}`, exp && `· ${exp}`].filter(Boolean).join(' '),
    }),
  },
})
