import {defineArrayMember, defineField, defineType} from 'sanity'
import {PageSectionVisibleField} from '../components/pageSection/PageSectionVisibleField'
import {HomeSourceListReadout} from '../components/homePage/HomeSourceListReadout'

const pageSectionVisibleUi = (sectionKey, group) =>
  defineField({
    name: `${sectionKey}SectionVisibilityUi`,
    title: 'Section visibility',
    type: 'string',
    group,
    components: {input: PageSectionVisibleField},
    options: {sectionKey},
  })

const heroCardRow = {
  type: 'object',
  name: 'heroCardRow',
  title: 'Row',
  fields: [
    {name: 'label', title: 'Label', type: 'string'},
    {name: 'value', title: 'Value', type: 'string'},
  ],
  preview: {
    select: {l: 'label', v: 'value'},
    prepare({l, v}) {
      return {title: l || '—', subtitle: v}
    },
  },
}

const statItem = {
  type: 'object',
  name: 'homeStat',
  title: 'Stat',
  fields: [
    {name: 'number', title: 'Number', type: 'string'},
    {name: 'label', title: 'Label', type: 'string'},
  ],
  preview: {
    select: {n: 'number', l: 'label'},
    prepare({n, l}) {
      return {title: n || '—', subtitle: l}
    },
  },
}

const missionItem = {
  type: 'object',
  name: 'missionItem',
  title: 'Mission item',
  fields: [
    {
      name: 'iconType',
      title: 'Icon type',
      type: 'string',
      options: {
        list: [
          {title: 'Transport', value: 'transport'},
          {title: 'Lodge', value: 'lodge'},
          {title: 'Tech', value: 'tech'},
          {title: 'Group', value: 'group'},
          {title: 'Conservation', value: 'conservation'},
        ],
        layout: 'dropdown',
      },
    },
    {name: 'title', title: 'Title', type: 'string'},
    {name: 'subtitle', title: 'Subtitle', type: 'string'},
  ],
  preview: {
    select: {t: 'title', i: 'iconType'},
    prepare({t, i}) {
      return {title: t || 'Item', subtitle: i}
    },
  },
}

const bookingTrustItem = {
  type: 'object',
  name: 'bookingTrustItem',
  title: 'Trust item',
  fields: [
    {
      name: 'iconType',
      title: 'Icon type',
      type: 'string',
      options: {
        list: [
          {title: 'Shield', value: 'shield'},
          {title: 'Chart', value: 'chart'},
          {title: 'Heart', value: 'heart'},
          {title: 'Clock', value: 'clock'},
        ],
        layout: 'dropdown',
      },
    },
    {name: 'text', title: 'Text', type: 'string'},
  ],
  preview: {
    select: {t: 'text', i: 'iconType'},
    prepare({t, i}) {
      return {title: t || '—', subtitle: i}
    },
  },
}

const labelValue = {
  type: 'object',
  name: 'labelValue',
  title: 'Label & value',
  fields: [
    {name: 'label', title: 'Label', type: 'string'},
    {name: 'value', title: 'Value', type: 'string'},
  ],
  preview: {
    select: {l: 'label', v: 'value'},
    prepare({l, v}) {
      return {title: l, subtitle: v}
    },
  },
}

const explorerFilterTab = {
  type: 'object',
  name: 'homeExplorerFilterTab',
  title: 'Filter tab',
  fields: [
    {
      name: 'filterKey',
      title: 'Filter',
      type: 'string',
      options: {
        list: [
          {title: 'All', value: 'all'},
          {title: 'Nature Core', value: 'nature'},
          {title: 'Family Adventure', value: 'family'},
          {title: 'Exp. Learning', value: 'learning'},
          {title: 'Tailor Made', value: 'tailor'},
        ],
        layout: 'dropdown',
      },
      validation: (Rule) => Rule.required(),
    },
    {name: 'label', title: 'Label (visible)', type: 'string', validation: (Rule) => Rule.required()},
  ],
  preview: {
    select: {k: 'filterKey', l: 'label'},
    prepare({k, l}) {
      return {title: l || k || 'Tab', subtitle: k}
    },
  },
}

export const homePage = defineType({
  name: 'homePage',
  title: 'Home page',
  type: 'document',
  groups: [
    {name: 'meta', title: 'SEO & metadata'},
    {name: 'hero', title: 'Hero', default: true},
    {name: 'stats', title: 'Stats'},
    {name: 'manifesto', title: 'Manifesto'},
    {name: 'explorer', title: 'Experiences'},
    {name: 'reviews', title: 'Reviews'},
    {name: 'tech', title: 'Tech'},
    {name: 'mission', title: 'Mission'},
    {name: 'partners', title: 'Partners'},
    {name: 'blog', title: 'Blog'},
    {name: 'booking', title: 'Booking CTA'},
  ],
  fields: [
    defineField({
      name: 'seo',
      title: 'SEO (home /)',
      type: 'seo',
      group: 'meta',
    }),
    defineField({
      name: 'sectionModules',
      title: 'sectionModules (internal)',
      type: 'array',
      of: [{type: 'pageModule'}],
      hidden: true,
    }),
    pageSectionVisibleUi('hero', 'hero'),
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
    }),
    defineField({
      name: 'heroEyebrow',
      title: 'Eyebrow (location line)',
      type: 'string',
      group: 'hero',
    }),
    defineField({name: 'heroHeadline', title: 'Headline (bold)', type: 'string', group: 'hero'}),
    defineField({name: 'heroHeadlineLight', title: 'Headline (light)', type: 'string', group: 'hero'}),
    defineField({name: 'heroSubheadline', title: 'Subheadline', type: 'text', group: 'hero', rows: 3}),
    defineField({
      name: 'heroPills',
      title: 'Hero pills',
      type: 'array',
      of: [{type: 'string'}],
      group: 'hero',
    }),
    defineField({
      name: 'heroCta1Text',
      title: 'CTA 1 text (legacy)',
      type: 'string',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroCta1Link',
      title: 'CTA 1 link (legacy)',
      type: 'string',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroCta1SmartLink',
      title: 'CTA 1',
      type: 'smartLink',
      group: 'hero',
      description: 'Primary editor control for the first hero button.',
    }),
    defineField({
      name: 'heroCta2Text',
      title: 'CTA 2 text (legacy)',
      type: 'string',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroCta2Link',
      title: 'CTA 2 link (legacy)',
      type: 'string',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroCta2SmartLink',
      title: 'CTA 2',
      type: 'smartLink',
      group: 'hero',
      description: 'Primary editor control for the second hero button.',
    }),
    defineField({name: 'heroCardPrice', title: 'Hero card — price', type: 'string', group: 'hero'}),
    defineField({
      name: 'heroCardPriceSuffix',
      title: 'Hero card — price line suffix',
      type: 'string',
      description: 'e.g. “per person” or “/person” (small text beside the price).',
      initialValue: '/person',
      group: 'hero',
    }),
    defineField({name: 'heroCardSubprice', title: 'Hero card — subprice line', type: 'string', group: 'hero'}),
    defineField({name: 'heroCardRows', title: 'Hero card — rows', type: 'array', of: [heroCardRow], group: 'hero'}),
    defineField({
      name: 'heroCardCtaText',
      title: 'Hero card — CTA text (legacy)',
      type: 'string',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroCardCtaLink',
      title: 'Hero card — CTA link (legacy)',
      type: 'string',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroCardCtaSmartLink',
      title: 'Hero card — CTA',
      type: 'smartLink',
      group: 'hero',
      description: 'Primary editor control for the hero card button.',
    }),
    defineField({
      name: 'heroScrollLabel',
      title: 'Scroll indicator label',
      type: 'string',
      description: 'Short word next to the scroll line (e.g. “scroll”).',
      group: 'hero',
    }),
    defineField({
      name: 'heroImageFallbackUrl',
      title: 'Hero image fallback URL',
      type: 'url',
      description: 'Used when no hero image asset is set (technical fallback).',
      group: 'hero',
    }),

    pageSectionVisibleUi('stats', 'stats'),
    defineField({
      name: 'stats',
      title: 'Stats (4 items)',
      type: 'array',
      of: [statItem],
      validation: (Rule) => Rule.max(4).min(0),
      group: 'stats',
    }),

    pageSectionVisibleUi('manifesto', 'manifesto'),
    defineField({name: 'manifestoEyebrow', title: 'Eyebrow', type: 'string', group: 'manifesto'}),
    defineField({name: 'manifestoHeadline', title: 'Headline', type: 'string', group: 'manifesto'}),
    defineField({name: 'manifestoBody1', title: 'Body 1', type: 'text', group: 'manifesto', rows: 4}),
    defineField({name: 'manifestoBody2', title: 'Body 2', type: 'text', group: 'manifesto', rows: 4}),
    defineField({
      name: 'manifestoImage',
      title: 'Image',
      type: 'image',
      group: 'manifesto',
      options: {hotspot: true},
    }),
    defineField({name: 'manifestoImageCaption', title: 'Image caption', type: 'string', group: 'manifesto'}),
    defineField({
      name: 'manifestoCta1Text',
      title: 'CTA 1 text (legacy)',
      type: 'string',
      group: 'manifesto',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'manifestoCta1Link',
      title: 'CTA 1 link (legacy)',
      type: 'string',
      group: 'manifesto',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'manifestoCta1SmartLink',
      title: 'CTA 1',
      type: 'smartLink',
      group: 'manifesto',
    }),
    defineField({
      name: 'manifestoCta2Text',
      title: 'CTA 2 text (legacy)',
      type: 'string',
      group: 'manifesto',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'manifestoCta2Link',
      title: 'CTA 2 link (legacy)',
      type: 'string',
      group: 'manifesto',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'manifestoCta2SmartLink',
      title: 'CTA 2',
      type: 'smartLink',
      group: 'manifesto',
    }),

    pageSectionVisibleUi('explorer', 'explorer'),
    defineField({name: 'explorerEyebrow', title: 'Eyebrow', type: 'string', group: 'explorer'}),
    defineField({name: 'explorerHeadline', title: 'Title', type: 'string', group: 'explorer'}),
    defineField({
      name: 'explorerSubheadline',
      title: 'Body text',
      type: 'text',
      group: 'explorer',
      rows: 3,
    }),
    defineField({
      name: 'explorerProgramGroups',
      title: 'Program types to show',
      type: 'array',
      of: [{type: 'homeExperienceProgramGroup'}],
      group: 'explorer',
      description:
        'Choose which experience program types appear as filter tabs and in what order. Cards load from published experiences in the CMS.',
    }),
    defineField({
      name: 'explorerTailorBand',
      title: 'Tailor Made band',
      type: 'tailorMadeBand',
      group: 'explorer',
      description:
        'Shown on the site only when “Tailor Made” is included in program types above. Toggle “Show Tailor Made band”, then set eyebrow, title, subtitle, and CTA smart link.',
    }),
    defineField({
      name: 'explorerFilterTabs',
      title: 'Filter tabs (legacy)',
      type: 'array',
      of: [explorerFilterTab],
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerPriceEnquireLabel',
      title: 'Price label — enquire (legacy)',
      type: 'string',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerPriceCustomLabel',
      title: 'Price label — custom (legacy)',
      type: 'string',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerCardCtaViewLabel',
      title: 'Card CTA — view (legacy)',
      type: 'string',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerCardCtaEnquireLabel',
      title: 'Card CTA — enquire (legacy)',
      type: 'string',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerTailorRouteDurationLabel',
      title: 'Tailor card — route badge (legacy)',
      type: 'string',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerTailorDescriptionFallback',
      title: 'Tailor card — description (legacy)',
      type: 'text',
      rows: 2,
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerTailorCtaText',
      title: 'Tailor card — CTA text (legacy)',
      type: 'string',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerTailorWhatsappUrl',
      title: 'Tailor card — WhatsApp URL (legacy)',
      type: 'url',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerTailorWhatsappSmartLink',
      title: 'Tailor card — WhatsApp (legacy)',
      type: 'smartLink',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerLearningBadgeLabels',
      title: 'Exp. learning badges (legacy)',
      type: 'array',
      of: [{type: 'string'}],
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerEmptyGridMessage',
      title: 'Empty grid — message (legacy)',
      type: 'text',
      rows: 3,
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerEmptyGridLinkLabel',
      title: 'Empty grid — link label (legacy)',
      type: 'string',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerEmptyGridLinkHref',
      title: 'Empty grid — link URL (legacy)',
      type: 'string',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerEmptyGridSmartLink',
      title: 'Empty grid — link (legacy)',
      type: 'smartLink',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerCardImageFallbackUrl',
      title: 'Card image fallback URL (legacy)',
      type: 'url',
      group: 'explorer',
      hidden: true,
    }),
    defineField({
      name: 'explorerCatalogReadout',
      title: 'Experience catalog (read-only)',
      type: 'text',
      rows: 1,
      group: 'explorer',
      readOnly: true,
      hidden: true,
      components: {input: HomeSourceListReadout},
      options: {catalog: 'experiences'},
    }),

    pageSectionVisibleUi('reviews', 'reviews'),
    defineField({
      name: 'reviewsSection',
      title: 'Reviews section',
      type: 'pageReviewsSection',
      group: 'reviews',
      description:
        'Eyebrow, title, optional body, rotating quotes (max 3), carousel cards (max 4). Global rating/trust badge comes from Settings → Reviews — global summary.',
    }),
    defineField({name: 'reviewsEyebrow', title: 'Legacy — eyebrow', type: 'string', group: 'reviews', hidden: true}),
    defineField({name: 'reviewsHeadline', title: 'Legacy — headline', type: 'string', group: 'reviews', hidden: true}),
    defineField({
      name: 'reviewsBody',
      title: 'Legacy — body',
      type: 'text',
      rows: 4,
      group: 'reviews',
      hidden: true,
    }),
    defineField({
      name: 'reviewsScore',
      title: 'Legacy — score',
      type: 'string',
      group: 'reviews',
      hidden: true,
    }),
    defineField({
      name: 'reviewsSourceLabel',
      title: 'Legacy — source',
      type: 'string',
      group: 'reviews',
      hidden: true,
    }),
    defineField({
      name: 'reviewsEmptyMessage',
      title: 'Legacy — empty message',
      type: 'text',
      rows: 3,
      group: 'reviews',
      hidden: true,
    }),
    defineField({
      name: 'homeSelectedReviews',
      title: 'Legacy — review order',
      type: 'array',
      group: 'reviews',
      hidden: true,
      of: [
        defineArrayMember({
          type: 'reference',
          to: [{type: 'review'}],
          options: {disableNew: true},
        }),
      ],
      validation: (Rule) => Rule.unique(),
    }),

    pageSectionVisibleUi('tech', 'tech'),
    defineField({name: 'techEyebrow', title: 'Eyebrow', type: 'string', group: 'tech'}),
    defineField({name: 'techHeadline', title: 'Headline', type: 'string', group: 'tech'}),
    defineField({name: 'techBody', title: 'Body', type: 'text', group: 'tech', rows: 4}),
    defineField({
      name: 'technologyCatalogReadout',
      title: 'Tech product catalog (read-only)',
      type: 'text',
      rows: 1,
      group: 'tech',
      readOnly: true,
      components: {input: HomeSourceListReadout},
      options: {catalog: 'technologyProducts'},
    }),
    defineField({
      name: 'homeSelectedTechnologyProducts',
      title: 'Tech products on Home (order)',
      type: 'array',
      group: 'tech',
      description:
        'Optional curated list and order. Leave empty to fall back to site rules (e.g. all products). Edit each product under Content → Tech product.',
      of: [
        defineArrayMember({
          type: 'reference',
          to: [{type: 'technologyProduct'}],
          options: {disableNew: true},
        }),
      ],
      validation: (Rule) => Rule.unique(),
    }),

    pageSectionVisibleUi('mission', 'mission'),
    defineField({name: 'missionEyebrow', title: 'Eyebrow', type: 'string', group: 'mission'}),
    defineField({name: 'missionHeadline', title: 'Headline', type: 'string', group: 'mission'}),
    defineField({name: 'missionBody', title: 'Body', type: 'text', group: 'mission', rows: 4}),
    defineField({name: 'missionItems', title: 'Items', type: 'array', of: [missionItem], group: 'mission'}),
    defineField({
      name: 'missionCtaText',
      title: 'CTA text (legacy)',
      type: 'string',
      group: 'mission',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'missionCtaLink',
      title: 'CTA link (legacy)',
      type: 'string',
      group: 'mission',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'missionCtaSmartLink',
      title: 'Mission — CTA',
      type: 'smartLink',
      group: 'mission',
    }),
    defineField({name: 'missionPhoto1', title: 'Photo 1', type: 'image', group: 'mission', options: {hotspot: true}}),
    defineField({name: 'missionPhoto2', title: 'Photo 2', type: 'image', group: 'mission', options: {hotspot: true}}),
    defineField({name: 'missionPhoto3', title: 'Photo 3', type: 'image', group: 'mission', options: {hotspot: true}}),

    pageSectionVisibleUi('partners', 'partners'),
    defineField({
      name: 'partnersEyebrow',
      title: 'Eyebrow (optional)',
      type: 'string',
      group: 'partners',
      description: 'Small line above the partners section title.',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'partnersTitle',
      title: 'Section title',
      type: 'string',
      group: 'partners',
      validation: (Rule) => Rule.max(160),
    }),
    defineField({
      name: 'partnersBody',
      title: 'Body',
      type: 'text',
      rows: 4,
      group: 'partners',
      description: 'Optional text under the title.',
    }),
    defineField({
      name: 'partnersEmptyMessage',
      title: 'When no partners selected — message (optional)',
      type: 'text',
      rows: 3,
      group: 'partners',
      description:
        'If no partners are selected below, show this text instead of the logo row. Leave empty to hide the band when the list is empty.',
    }),
    defineField({
      name: 'partnersOnHome',
      title: 'Partners on Home (order)',
      type: 'array',
      group: 'partners',
      description:
        'Select which partners appear on the Home page and drag to reorder. Names, logos, links, and type are edited only on each Partner document — not here.',
      of: [
        defineArrayMember({
          type: 'reference',
          to: [{type: 'partner'}],
          options: {disableNew: true},
        }),
      ],
      validation: (Rule) =>
        Rule.custom((refs) => {
          if (!Array.isArray(refs)) return true
          const ids = refs.map((r) => r?._ref).filter(Boolean)
          return new Set(ids).size === ids.length ? true : 'Each partner can only appear once'
        }),
    }),

    pageSectionVisibleUi('blog', 'blog'),
    defineField({name: 'blogEyebrow', title: 'Eyebrow', type: 'string', group: 'blog'}),
    defineField({name: 'blogHeadline', title: 'Headline', type: 'string', group: 'blog'}),
    defineField({
      name: 'blogAllPostsLabel',
      title: '“All posts” link label (legacy)',
      type: 'string',
      group: 'blog',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'blogAllPostsUrl',
      title: '“All posts” URL (legacy)',
      type: 'url',
      group: 'blog',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'blogAllPostsSmartLink',
      title: '“All posts” link',
      type: 'smartLink',
      group: 'blog',
    }),
    defineField({
      name: 'blogReadLabel',
      title: 'Card “Read” link label',
      type: 'string',
      group: 'blog',
    }),
    defineField({
      name: 'blogFallbackCategory',
      title: 'Fallback category tag',
      type: 'string',
      group: 'blog',
      description: 'When a post has no category in CMS.',
    }),
    defineField({
      name: 'blogFallbackReadingMinutes',
      title: 'Fallback reading time (minutes)',
      type: 'number',
      group: 'blog',
    }),
    defineField({
      name: 'blogEmptyMessage',
      title: 'When no posts load — message',
      type: 'text',
      rows: 3,
      group: 'blog',
    }),
    defineField({
      name: 'blogFallbackPostHref',
      title: 'Card link fallback (no external URL / slug)',
      type: 'string',
      group: 'blog',
      description: 'e.g. #blog or https://… Used when a post has no external link or slug.',
    }),
    defineField({
      name: 'blogBody',
      title: 'Intro / body',
      type: 'text',
      rows: 4,
      group: 'blog',
      description: 'Optional intro under the blog heading on Home (when the site reads this field).',
    }),
    defineField({
      name: 'blogCatalogReadout',
      title: 'Blog post catalog (read-only)',
      type: 'text',
      rows: 1,
      group: 'blog',
      readOnly: true,
      components: {input: HomeSourceListReadout},
      options: {catalog: 'blogPosts'},
    }),
    defineField({
      name: 'homeSelectedBlogPosts',
      title: 'Blog posts on Home (order)',
      type: 'array',
      group: 'blog',
      description:
        'Drag to set order. Titles, images, and links are edited on each Blog post — not here.',
      of: [
        defineArrayMember({
          type: 'reference',
          to: [{type: 'blogPost'}],
          options: {disableNew: true},
        }),
      ],
      validation: (Rule) => Rule.unique(),
    }),

    pageSectionVisibleUi('booking', 'booking'),
    defineField({
      name: 'reserveCtaSettings',
      title: 'Reserve CTA (#book)',
      type: 'reserveCtaSettings',
      group: 'booking',
      description:
        'Primary editor for the final reserve block. Price defaults to the lowest **active** experience unless you set a price override.',
    }),
    defineField({
      name: 'bookingEyebrow',
      title: 'Eyebrow (legacy)',
      type: 'string',
      group: 'booking',
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'bookingHeadline',
      title: 'Headline (legacy)',
      type: 'string',
      group: 'booking',
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'bookingBody',
      title: 'Body (legacy)',
      type: 'text',
      group: 'booking',
      rows: 4,
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'bookingTrustItems',
      title: 'Trust items (legacy)',
      type: 'array',
      of: [bookingTrustItem],
      group: 'booking',
      hidden: true,
      description: 'Legacy — trust strip is fixed on the site.',
    }),
    defineField({
      name: 'bookingPrice',
      title: 'Price line (legacy)',
      type: 'string',
      group: 'booking',
      hidden: true,
      description: 'Legacy — derived from experiences or Reserve CTA override.',
    }),
    defineField({
      name: 'bookingPriceSuffixSmall',
      title: 'Price suffix (small) (legacy)',
      type: 'string',
      description: 'Legacy.',
      group: 'booking',
      hidden: true,
    }),
    defineField({
      name: 'bookingPriceSubtext',
      title: 'Price subtext (legacy)',
      type: 'string',
      group: 'booking',
      hidden: true,
    }),
    defineField({
      name: 'bookingCardRows',
      title: 'Card rows (legacy)',
      type: 'array',
      of: [labelValue],
      group: 'booking',
      hidden: true,
    }),
    defineField({
      name: 'bookingCta1Text',
      title: 'CTA 1 text (legacy)',
      type: 'string',
      group: 'booking',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'bookingCta1Link',
      title: 'CTA 1 link (legacy)',
      type: 'string',
      group: 'booking',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'bookingCta1SmartLink',
      title: 'CTA 1 (legacy)',
      type: 'smartLink',
      group: 'booking',
      hidden: true,
      description: 'Legacy — use Reserve CTA smart links.',
    }),
    defineField({
      name: 'bookingCta2Text',
      title: 'CTA 2 text (legacy)',
      type: 'string',
      group: 'booking',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'bookingCta2Link',
      title: 'CTA 2 link (legacy)',
      type: 'string',
      group: 'booking',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'bookingCta2SmartLink',
      title: 'CTA 2 (legacy)',
      type: 'smartLink',
      group: 'booking',
      hidden: true,
      description: 'Legacy — use Reserve CTA smart links.',
    }),
  ],
  preview: {
    prepare() {
      return {title: 'Home page'}
    },
  },
})
