import {defineField, defineType} from 'sanity'

const PROGRAMME_CATEGORY_OPTIONS = [
  {title: 'Volunteering', value: 'volunteering'},
  {title: 'Science field learning', value: 'science-field-learning'},
  {title: 'Multimedia learning', value: 'multimedia-learning'},
  {title: 'University programme', value: 'university-programme'},
  {title: 'Custom learning', value: 'custom-learning'},
]

const STATUS_OPTIONS = [
  {title: 'Active (visible & bookable)', value: 'active'},
  {title: 'Coming soon (visible without booking)', value: 'coming-soon'},
]

const imgHot = {hotspot: true}

/** Experiential Learning programme — canonical content for `/experiences/[slug]` learning landings. */
export const learningProgramme = defineType({
  name: 'learningProgramme',
  title: 'Learning Programme',
  type: 'document',
  groups: [
    {name: 'identity', title: 'General', default: true},
    {name: 'media', title: 'Media'},
    {name: 'overview', title: 'Overview'},
    {name: 'snapshotHighlights', title: 'Highlights'},
    {name: 'programme', title: 'Programme'},
    {name: 'typicalDay', title: 'Typical day'},
    {name: 'projects', title: 'Projects'},
    {name: 'outcomes', title: 'Outcomes'},
    {name: 'mentor', title: 'Mentor'},
    {name: 'applicationProcess', title: 'Application Process'},
    {name: 'fieldBase', title: 'Field base'},
    {name: 'wildlife', title: 'Wildlife'},
    {name: 'logistics', title: 'Included'},
    {name: 'resources', title: 'Resources'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'identity',
      validation: (Rule) => [Rule.required(), Rule.max(80)],
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'identity',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
      description: 'Public URL: /experiences/{slug}',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'identity',
      options: {list: STATUS_OPTIONS, layout: 'radio'},
      initialValue: 'active',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'programmeCategory',
      title: 'Programme category',
      type: 'string',
      group: 'identity',
      options: {list: PROGRAMME_CATEGORY_OPTIONS, layout: 'radio'},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'routeRef',
      title: 'Route / territory',
      type: 'reference',
      to: [{type: 'route'}],
      group: 'identity',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short description',
      type: 'text',
      group: 'identity',
      rows: 3,
      validation: (Rule) => Rule.max(160),
      description: 'For cards and listings.',
    }),
    defineField({
      name: 'durationDisplay',
      title: 'Duration display',
      type: 'string',
      group: 'identity',
      validation: (Rule) => Rule.max(40),
      description: 'Optional label for cards and hero, e.g. “2–8 weeks”.',
    }),
    defineField({
      name: 'price',
      title: 'Price (USD)',
      type: 'number',
      group: 'identity',
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: 'priceLabel',
      title: 'Price label',
      type: 'string',
      group: 'identity',
      validation: (Rule) => Rule.max(40),
    }),
    defineField({
      name: 'mainImage',
      title: 'Hero image',
      type: 'image',
      group: 'media',
      options: imgHot,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      group: 'media',
      of: [{type: 'experienceGalleryItem'}],
      validation: (Rule) => Rule.max(30),
    }),
    defineField({
      name: 'overviewHighlights',
      title: 'Overview highlight lines',
      type: 'array',
      group: 'overview',
      of: [{type: 'string', validation: (Rule) => Rule.max(100)}],
      validation: (Rule) => Rule.max(8),
      description:
        'Plain-text bullets for the Overview section on linked Experience Pages (same role as Experience KC → Overview · datos). Not the stats bar under the hero.',
    }),
    defineField({
      name: 'snapshotHighlights',
      title: 'Snapshot highlights (stats bar)',
      type: 'array',
      group: 'snapshotHighlights',
      of: [{type: 'experienceSnapshotHighlight'}],
      validation: (Rule) => Rule.max(8),
      description:
        'Title + subtitle pairs for the highlight bar directly under the hero (e.g. “2–8 weeks” / “Duration”). Each Experience Page picks up to 6. Not the Overview bullet list.',
    }),
    defineField({
      name: 'howItWorksPillTitle',
      title: 'How it works pill title',
      type: 'string',
      group: 'programme',
      initialValue: 'How it works',
      validation: (Rule) => Rule.max(40),
      description: 'Label on the first tab pill inside the Programme section.',
    }),
    defineField({
      name: 'howItWorksIntro',
      title: 'How it works intro',
      type: 'text',
      group: 'programme',
      rows: 3,
      validation: (Rule) => Rule.max(500),
    }),
    defineField({
      name: 'howItWorksImage',
      title: 'How it works image',
      type: 'image',
      group: 'programme',
      options: imgHot,
    }),
    defineField({
      name: 'howItWorksImageCaption',
      title: 'How it works image caption',
      type: 'string',
      group: 'programme',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'howItWorksSteps',
      title: 'How it works steps',
      type: 'array',
      group: 'programme',
      of: [{type: 'learningProgrammeStep'}],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'typicalDayPillTitle',
      title: 'Typical day pill title',
      type: 'string',
      group: 'typicalDay',
      initialValue: 'Typical day',
      validation: (Rule) => Rule.max(40),
      description: 'Label on the Typical day tab pill inside the Programme section.',
    }),
    defineField({
      name: 'typicalDayIntro',
      title: 'Typical day intro',
      type: 'text',
      group: 'typicalDay',
      rows: 3,
      validation: (Rule) => Rule.max(500),
    }),
    defineField({
      name: 'typicalDayImage',
      title: 'Typical day image',
      type: 'image',
      group: 'typicalDay',
      options: imgHot,
    }),
    defineField({
      name: 'typicalDayImageCaption',
      title: 'Typical day image caption',
      type: 'string',
      group: 'typicalDay',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'typicalDayRows',
      title: 'Typical day rows',
      type: 'array',
      group: 'typicalDay',
      of: [{type: 'learningProgrammeTypicalDayRow'}],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'typicalDayNote',
      title: 'Typical day footnote',
      type: 'text',
      group: 'typicalDay',
      rows: 2,
      validation: (Rule) => Rule.max(400),
    }),
    defineField({
      name: 'projects',
      title: 'Projects you can join',
      type: 'array',
      group: 'projects',
      of: [{type: 'learningProgrammeProject'}],
      validation: (Rule) => Rule.max(12),
      description: 'Front-end shows up to 6 cards.',
    }),
    defineField({
      name: 'learningOutcomes',
      title: 'Learning outcomes',
      type: 'array',
      group: 'outcomes',
      of: [{type: 'learningProgrammeOutcome'}],
      validation: (Rule) => Rule.max(8),
    }),
    defineField({
      name: 'mentorTabLabel',
      title: 'Mentor tab label',
      type: 'string',
      group: 'mentor',
      initialValue: 'Mentor',
      validation: (Rule) => Rule.max(40),
      description: 'Label on the Mentor pill inside the Programme section. Not shown in tab content.',
    }),
    defineField({
      name: 'mentors',
      title: 'Mentors & programme leads',
      type: 'array',
      group: 'mentor',
      of: [{type: 'learningProgrammeMentor'}],
      validation: (Rule) => Rule.max(8),
      description:
        'Add one or more mentors or programme leads for internship-style programmes. Order here is the order on the website. Leave empty to hide the Mentor tab.',
    }),
    defineField({
      name: 'mentorName',
      title: 'Name (legacy)',
      type: 'string',
      group: 'mentor',
      hidden: true,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: 'mentorRole',
      title: 'Role / position (legacy)',
      type: 'string',
      group: 'mentor',
      hidden: true,
      validation: (Rule) => Rule.max(80),
    }),
    defineField({
      name: 'mentorPhoto',
      title: 'Photo (legacy)',
      type: 'image',
      group: 'mentor',
      hidden: true,
      options: imgHot,
    }),
    defineField({
      name: 'mentorBiography',
      title: 'Short biography (legacy)',
      type: 'text',
      group: 'mentor',
      hidden: true,
      rows: 5,
      validation: (Rule) => Rule.max(1200),
    }),
    defineField({
      name: 'mentorAchievements',
      title: 'Key achievements (legacy)',
      type: 'array',
      group: 'mentor',
      hidden: true,
      of: [{type: 'string', validation: (Rule) => Rule.max(120)}],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'mentorSkills',
      title: 'Skills & experience (legacy)',
      type: 'array',
      group: 'mentor',
      hidden: true,
      of: [{type: 'string', validation: (Rule) => Rule.max(80)}],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'applicationProcessTabLabel',
      title: 'Application process tab label',
      type: 'string',
      group: 'applicationProcess',
      initialValue: 'Application process',
      validation: (Rule) => Rule.max(40),
      description: 'Label on the Application process pill inside the Programme section. Not shown in tab content.',
    }),
    defineField({
      name: 'applicationProcessIntro',
      title: 'Intro text',
      type: 'text',
      group: 'applicationProcess',
      rows: 3,
      validation: (Rule) => Rule.max(600),
    }),
    defineField({
      name: 'applicationProcessSteps',
      title: 'Process steps',
      type: 'array',
      group: 'applicationProcess',
      of: [{type: 'learningProgrammeApplicationStep'}],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'lodgePresentationRows',
      title: 'Lodges on this programme',
      type: 'array',
      group: 'fieldBase',
      of: [{type: 'experienceLodgePresentationRow'}],
      description:
        'Same as Experience KC → **Lodges on this programme**. One row per lodge/field base. Card image, name, description, and chips come from each lodge’s **Lodge Page**. Curate order on the linked Experience Page → Lodge tab.',
      validation: (Rule) => Rule.max(8),
    }),
    defineField({
      name: 'fieldBaseRef',
      title: 'Field base / lodge (legacy single ref)',
      type: 'reference',
      to: [{type: 'lodge'}],
      group: 'fieldBase',
      hidden: ({document}) => Array.isArray(document?.lodgePresentationRows) && document.lodgePresentationRows.length > 0,
      description:
        'Legacy — prefer **Lodges on this programme** above. Used only when that list is empty.',
    }),
    defineField({
      name: 'fieldBaseOverrideTitle',
      title: 'Field base title override',
      type: 'string',
      group: 'fieldBase',
      validation: (Rule) => Rule.max(120),
    }),
    defineField({
      name: 'fieldBaseOverrideText',
      title: 'Field base intro override',
      type: 'text',
      group: 'fieldBase',
      rows: 4,
      validation: (Rule) => Rule.max(800),
    }),
    defineField({
      name: 'wildlife',
      title: 'Wildlife species',
      type: 'array',
      group: 'wildlife',
      of: [{type: 'experienceWildlifeItem'}],
      validation: (Rule) => Rule.max(10),
      description:
        'Species cards for linked Experience Pages. Order on the public page is curated on the Experience Page → Wildlife tab.',
    }),
    defineField({
      name: 'includes',
      title: 'Included',
      type: 'array',
      group: 'logistics',
      of: [{type: 'string', validation: (Rule) => Rule.max(80)}],
      validation: (Rule) => Rule.max(15),
    }),
    defineField({
      name: 'notIncludes',
      title: 'Not included',
      type: 'array',
      group: 'logistics',
      of: [{type: 'string', validation: (Rule) => Rule.max(80)}],
      validation: (Rule) => Rule.max(10),
    }),
    defineField({
      name: 'resources',
      title: 'Resources',
      type: 'array',
      group: 'resources',
      of: [{type: 'experienceResourceCard'}],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
      description:
        'Optional programme-level SEO fallbacks. Public URL meta is primarily controlled on the linked Experience Page.',
    }),
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'programmeCategory',
      media: 'mainImage',
      status: 'status',
    },
    prepare: ({title, subtitle, media, status}) => ({
      title: title || 'Learning programme',
      subtitle: [subtitle, status].filter(Boolean).join(' · '),
      media,
    }),
  },
})
