import {defineField, defineType} from 'sanity'

/**
 * Single URL for `/routes` — all sections inline (no `route` document refs as source of truth).
 */
export const routesPage = defineType({
  name: 'routesPage',
  title: 'Routes page',
  type: 'document',
  groups: [
    {name: 'general', title: 'General & SEO', default: true},
    {name: 'hero', title: 'Hero'},
    {name: 'snapshot', title: 'Snapshot bar'},
    {name: 'territory', title: 'Territory'},
    {name: 'routeCards', title: 'Route cards'},
    {name: 'compare', title: 'Comparison table'},
    {name: 'experiences', title: 'Experiences grid'},
    {name: 'reviews', title: 'Reviews'},
    {name: 'finalCta', title: 'Final CTA'},
  ],
  fields: [
    defineField({
      name: 'internalTitle',
      title: 'Internal title (Studio only)',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'slug',
      title: 'Slug / URL',
      type: 'slug',
      group: 'general',
      options: {source: 'internalTitle', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'general',
    }),

    // --- Hero ---
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      type: 'image',
      group: 'hero',
      options: {hotspot: true},
    }),
    defineField({name: 'heroImageAlt', title: 'Hero image alt', type: 'string', group: 'hero'}),
    defineField({name: 'heroEyebrow', title: 'Eyebrow', type: 'string', group: 'hero'}),
    defineField({name: 'heroTitleLine1', title: 'Title line 1', type: 'string', group: 'hero'}),
    defineField({name: 'heroTitleLine2', title: 'Title line 2', type: 'string', group: 'hero'}),
    defineField({name: 'heroTagline', title: 'Tagline', type: 'text', rows: 3, group: 'hero'}),
    defineField({
      name: 'heroPrimaryCta',
      title: 'Primary CTA (legacy)',
      type: 'linkWithLabel',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroSecondaryCta',
      title: 'Secondary CTA (legacy)',
      type: 'linkWithLabel',
      group: 'hero',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'heroPrimarySmartLink',
      title: 'Primary CTA',
      type: 'smartLink',
      group: 'hero',
      description: 'Primary editor control for the hero button.',
    }),
    defineField({
      name: 'heroSecondarySmartLink',
      title: 'Secondary CTA',
      type: 'smartLink',
      group: 'hero',
      description: 'Primary editor control for the secondary hero button.',
    }),

    // --- Snapshot ---
    defineField({
      name: 'snapshotStats',
      title: 'Snapshot stats',
      type: 'array',
      group: 'snapshot',
      of: [{type: 'routesPageStatLine'}],
      validation: (Rule) => Rule.max(8),
    }),

    // --- Territory ---
    defineField({name: 'territorySectionId', title: 'Section HTML id', type: 'string', group: 'territory', initialValue: 'territory'}),
    defineField({name: 'territoryEyebrow', title: 'Eyebrow', type: 'string', group: 'territory'}),
    defineField({name: 'territoryH2', title: 'Heading', type: 'string', group: 'territory'}),
    defineField({name: 'territoryBody', title: 'Body', type: 'text', rows: 4, group: 'territory'}),
    defineField({
      name: 'territoryStrip',
      title: 'Strip chips',
      type: 'array',
      group: 'territory',
      of: [{type: 'routesPageTerritoryStripChip'}],
      validation: (Rule) => Rule.max(6),
    }),

    // --- Route cards ---
    defineField({
      name: 'routeCards',
      title: 'Route cards',
      type: 'array',
      group: 'routeCards',
      of: [{type: 'routesPageRouteCard'}],
      validation: (Rule) => Rule.max(6),
    }),

    // --- Compare ---
    defineField({name: 'compareSectionId', title: 'Section HTML id', type: 'string', group: 'compare', initialValue: 'compare'}),
    defineField({name: 'compareEyebrow', title: 'Eyebrow', type: 'string', group: 'compare'}),
    defineField({name: 'compareH2', title: 'Heading', type: 'string', group: 'compare'}),
    defineField({name: 'compareIntro', title: 'Intro', type: 'text', rows: 3, group: 'compare'}),
    defineField({
      name: 'compareColumns',
      title: 'Columns (3)',
      type: 'array',
      group: 'compare',
      of: [{type: 'routesPageCompareColumn'}],
      validation: (Rule) => Rule.required().min(3).max(3),
    }),
    defineField({
      name: 'compareRows',
      title: 'Rows',
      type: 'array',
      group: 'compare',
      of: [
        {type: 'routesCompareRowText'},
        {type: 'routesCompareRowDots'},
        {type: 'routesCompareRowLodge'},
        {type: 'routesCompareRowBest'},
        {type: 'routesCompareRowPrice'},
      ],
    }),

    // --- Experiences ---
    defineField({name: 'experiencesSectionId', title: 'Section HTML id', type: 'string', group: 'experiences', initialValue: 'experiences'}),
    defineField({name: 'experiencesEyebrow', title: 'Eyebrow', type: 'string', group: 'experiences'}),
    defineField({name: 'experiencesH2', title: 'Heading', type: 'string', group: 'experiences'}),
    defineField({name: 'experiencesIntro', title: 'Intro', type: 'text', rows: 3, group: 'experiences'}),
    defineField({
      name: 'experiencesAllLabel',
      title: '“See all” link label (legacy)',
      type: 'string',
      group: 'experiences',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'experiencesAllHref',
      title: '“See all” link URL (legacy)',
      type: 'string',
      group: 'experiences',
      hidden: true,
      description: 'Legacy fallback — hidden from normal editing.',
    }),
    defineField({
      name: 'experiencesAllSmartLink',
      title: '“See all” link',
      type: 'smartLink',
      group: 'experiences',
      description: 'Primary editor control for the “see all” link below the grid.',
    }),
    defineField({
      name: 'selectedExperiences',
      title: 'Selected experiences (ordered)',
      type: 'array',
      group: 'experiences',
      of: [{type: 'reference', to: [{type: 'experience'}]}],
      validation: (Rule) => Rule.max(48),
      description: 'Primary source for the cards. If empty and fallback is enabled, the page uses all published experiences.',
    }),
    defineField({
      name: 'fallbackToAllExperiences',
      title: 'If no selected experiences, use all experiences',
      type: 'boolean',
      group: 'experiences',
      initialValue: true,
    }),
    defineField({
      name: 'experiencesFilters',
      title: 'Filter pills (optional)',
      description: 'If empty, the site uses default filters (All, Camanti, Manu Road, Manu Core).',
      type: 'array',
      group: 'experiences',
      of: [{type: 'routesPageExpFilterPill'}],
      validation: (Rule) => Rule.max(8),
    }),
    defineField({
      name: 'experienceCards',
      title: 'Experience cards (legacy fallback)',
      type: 'array',
      group: 'experiences',
      hidden: true,
      of: [{type: 'routesPageExpCard'}],
      validation: (Rule) => Rule.max(24),
      description:
        'Legacy manual cards — hidden in Studio; data preserved for resolver. Used only if references are empty and no experiences can be resolved.',
    }),

    // --- Reviews ---
    defineField({
      name: 'reviewsSection',
      title: 'Reviews section',
      type: 'pageReviewsSection',
      group: 'reviews',
      description: 'Global rating summary: Settings → Reviews — global summary.',
    }),
    defineField({
      name: 'reviewsFeaturedQuotes',
      title: 'Legacy — rotating quotes',
      type: 'array',
      group: 'reviews',
      hidden: true,
      of: [{type: 'routesPageFeaturedQuote'}],
      validation: (Rule) => Rule.max(12),
    }),
    defineField({
      name: 'reviewsRefs',
      title: 'Legacy — review refs',
      type: 'array',
      group: 'reviews',
      hidden: true,
      of: [{type: 'reference', to: [{type: 'review'}]}],
      validation: (Rule) => Rule.max(48),
    }),
    defineField({name: 'reviewsEyebrow', title: 'Legacy — eyebrow', type: 'string', group: 'reviews', hidden: true}),
    defineField({name: 'reviewsHeadline', title: 'Legacy — headline', type: 'string', group: 'reviews', hidden: true}),
    defineField({
      name: 'reviewsSectionLead',
      title: 'Legacy — intro',
      type: 'text',
      rows: 3,
      group: 'reviews',
      hidden: true,
    }),
    defineField({
      name: 'reviewsAverageRating',
      title: 'Legacy — rating text',
      type: 'string',
      group: 'reviews',
      hidden: true,
    }),
    defineField({name: 'reviewsSourceLabel', title: 'Legacy — source', type: 'string', group: 'reviews', hidden: true}),
    defineField({
      name: 'reviewsSecondaryRatingLine',
      title: 'Legacy — secondary line',
      type: 'string',
      group: 'reviews',
      hidden: true,
    }),

    // --- Final CTA ---
    defineField({name: 'finalCtaSectionId', title: 'Section HTML id', type: 'string', group: 'finalCta', initialValue: 'contact'}),
    defineField({
      name: 'reserveCtaSettings',
      title: 'Reserve CTA (final block)',
      type: 'reserveCtaSettings',
      group: 'finalCta',
      description:
        'Editorial + booking card. Price defaults to lowest **active** experience unless overridden.',
    }),
    defineField({
      name: 'finalCtaEyebrow',
      title: 'Eyebrow (legacy)',
      type: 'string',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'finalCtaH2',
      title: 'Heading (legacy)',
      type: 'string',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'finalCtaBody',
      title: 'Body (legacy)',
      type: 'text',
      rows: 4,
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — use Reserve CTA above.',
    }),
    defineField({
      name: 'finalCtaWhatsappSmartLink',
      title: 'WhatsApp (legacy)',
      type: 'smartLink',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — use Reserve CTA secondary smart link.',
    }),
    defineField({
      name: 'finalCtaSecondarySmartLink',
      title: 'Secondary CTA (legacy)',
      type: 'smartLink',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — use Reserve CTA primary smart link.',
    }),
    defineField({
      name: 'finalCtaWhatsappHref',
      title: 'WhatsApp URL (legacy fallback)',
      type: 'string',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — hidden in Studio; data preserved. Only used if WhatsApp smart link is empty.',
    }),
    defineField({
      name: 'finalCtaWhatsappLabel',
      title: 'WhatsApp label (legacy fallback)',
      type: 'string',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — hidden in Studio; data preserved.',
    }),
    defineField({
      name: 'finalCtaSecondaryHref',
      title: 'Secondary URL (legacy fallback)',
      type: 'string',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — hidden in Studio; data preserved.',
    }),
    defineField({
      name: 'finalCtaSecondaryLabel',
      title: 'Secondary label (legacy fallback)',
      type: 'string',
      group: 'finalCta',
      hidden: true,
      description: 'Legacy — hidden in Studio; data preserved.',
    }),
    defineField({
      name: 'finalCtaTrustItems',
      title: 'Trust strip (legacy)',
      type: 'array',
      group: 'finalCta',
      of: [{type: 'routesPageTrustItem'}],
      validation: (Rule) => Rule.max(8),
      hidden: true,
      description: 'Legacy — trust strip is fixed on the site.',
    }),
  ],
  preview: {
    select: {t: 'internalTitle', slug: 'slug.current'},
    prepare: ({t, slug}) => ({
      title: t || 'Routes page',
      subtitle: slug ? `/${slug}` : '',
    }),
  },
})
